spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: cafehi
    password: cafehi
    driver-class-name: oracle.jdbc.driver.OracleDriver

  mail:
    host: smtp.gmail.com
    port: 587
    username: CafeHi1004@gmail.com
    password: tabtmrxztjjejnav
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


mybatis:
  mapper-locations: mybatis/**/*.xml

logging:
  level:
    org.hibernate.sql: debug


server:
  error:
    path: /error

