spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: ${SMTP_SSL_ENABLE}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE}
        smtps:
          trust: ${SMTP_TRUST}

  s3:
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.sql: debug
